apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: demo-voting-app
    name: redis-service
spec:
  selector:
    app: demo-voting-app
    name: redis-pod
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
