apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: demo-voting-app
    name: voting-service
spec:
  selector:
    app: demo-voting-app
    name: voting-app-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30568
  type: NodePort
