apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: splunk-daemonset
  labels:
    app: splunk
spec:
  selector:
    matchLabels:
      app: splunk
  template:
    metadata:
      labels:
        app: splunk
    spec:
      containers:
        - name: splunk
          image: splunk/splunk:latest
          ports:
            - containerPort: 8000
            - containerPort: 8088
          env:
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_PASSWORD
              value: "yourpassword"
          volumeMounts:
            - name: splunk-data
              mountPath: /opt/splunk/var
      volumes:
        - name: splunk-data
          persistentVolumeClaim:
            claimName: splunk-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - us-south1-a
                        us-south1-b
                        us-south1-c
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - us-south1
#important point to note is that the name field in volumes should match the name field in volumeMounts: The name field in volumeMounts should match the name field in volumes
